language: node_js

node_js: 12

jobs:
  include:

  - stage: install, check code style and coverage
    if: tag IS blank
    services:
    - mongodb
    before_install:
    - curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.3.0/elasticsearch-2.3.0.deb && sudo dpkg -i --force-confnew elasticsearch-2.3.0.deb && sudo service elasticsearch start
    - sudo apt-get update && sudo apt-get install sendmail python make g++
    addons:
      hosts:
      - localhost
    before_script:
    - npm install -g grunt-cli
    - sleep 10
    script:
    - if [ "$TRAVIS_BRANCH" != "master" ]; then grunt test; fi
    - if [ "$TRAVIS_BRANCH" = "master" ]; then grunt coverage; fi

  - stage: Publish to npm
    if: branch =~ /(release)/
    script:
    - echo "PUBLISH npm"
    deploy:
      skip_cleanup: true
      provider: npm
      email: $NPM_EMAIL
      api_key: $NPM_TOKEN
      on:
        all_branches: true
        condition: $TRAVIS_BRANCH =~ ^(release)*

  - stage: Tag and release
    if: branch =~ /(release)/
    script:
    - echo "Tagging"
    - export PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -Fn '{ print $2 }' | sed 's/[n:",]//g' | tr -d '[[:space:]]')
    - export MAJOR_VERSION=$(echo ${PACKAGE_VERSION} | awk -F. '{ print $1 }')
    - echo Package version ${PACKAGE_VERSION}
    - echo Major version ${MAJOR_VERSION}

    - git config --local user.name ${GIT_USER}
    - git config --local user.email ${GIT_EMAIL}
    - git tag ${PACKAGE_VERSION}
    deploy:
      on:
        all_branches: true
      provider: releases
      api_key: ${GIT_TOKEN}
      skip_cleanup: true